### ISSUE TITLE
Noob question - Is there a way to render this inside React Native? 

### ISSUE THREAD

**Issue by foxnoodles** [samdauwe/BabylonCpp#60]
Any opensource components that could bind this to RN?  I mean this (in theory) should perform so much better than webview/webgl. On desktop in particular.

**Comment by samdauwe** [comment]
Hello,

you might have a look at [Babylon Native](https://github.com/BabylonJS/BabylonNative), that is currently under development and the [description page](https://medium.com/@babylonjs/babylon-native-821f1694fffc). In this project, the Babylon.js core engine is running in a JavaScript engine outside the browser, accessing the platform hardware (i.e. GPU) through an abstraction layer implemented in C++:

![babylon_js_native](https://user-images.githubusercontent.com/24841018/70174097-919bb500-16d4-11ea-88cd-287773cb4d67.png)

This project seems most interesting (and easier) to integrate with React Native. However, because there is a javascript engine in the picture and there is overhead due to the JavaScript to C++ communication this approach will use more memory and will potentially be slower compared to BabylonCpp where everything is in C++

For the moment I have no real idea which open source components that could be used to do the binding to RN. It is certainly possible but seems like a big effort.

Best regards,
Sam

**Comment by foxnoodles** [comment]
Hi, thanks for the reply,

Yeah I came across that one recently but it literally says: 

> This project is under heavy development. Not all intended platforms are currently implemented. DO NOT use in production code.

I need this for a desktop app (using RN Windows and Mac OS forks by MS), I never tried to test it but I'm pretty sure it won't work.

I mean I always implement it via Webview and send messages, I should work fine for basic 3D stuff even for huge scenes, as far as I don't overload it with complex shaders and post effects it will run just fine, but I wanted something better. 
Oh well, thank you tho

**Comment by samdauwe** [comment]
Hi,

Ah, probably the Webview approach you described is similar to [this one](https://doc.babylonjs.com/resources/babylonjs_and_react_native).The linked blog post on that page refers to a [git repo](https://github.com/JulienNoble/react-native-babylon-view-poc) that should allow to evaluate reactive native on windows with a test demo 3D scene, in case you need an example.

Indeed, Babylon native is still under heavy development and not yet meant to be used. For BabylonCpp to be usable in react native, the whole C++ API needs to be accessible to Javascript?

Best regards,
Sam

**Comment by foxnoodles** [comment]
Yeah, I'm currently testing that one. Works but debugging is a nightmare. 

as for the BabylonCPP, yeah either a custom wrapper/bridge or maybe there already exists something generic that does that. 

If I was to do it, I would have implemented it as a simple message dispatching system that can be accessed by both C++ an RN so they could share the same queue.

**Comment by samdauwe** [comment]
Yeah, I can imagine that is horrible to debug and you are forced to debug by using logging statements...

A possible approach to do the bindings is through the [WebIDL binder of Emscripten](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/WebIDL-Binder.html). It looks that these WebIDL files need to be created for every interface/class you want to expose to JavaScript. With the large api of babylonCpp this will become a huge effort if these WebIDL cannot be generated automatically. I did not find any tools for this yet.

The messaging dispatching system also sounds interesting but you probably are interesting in having a solution now instead of weeks or months.

The Webview approach seems to be the one to use on the short term.

**Comment by foxnoodles** [comment]
Yeah tons of logs... 


`Generating the bindings glue code
The bindings generator (tools/webidl_binder.py) takes a Web IDL file name and an output file name as inputs, and creates C++ and JavaScript glue code files.`

Hm, does this work? 



And yeah, I need something right now. I'mma still try the BabylonNative, just to make sure it doesn't work :D  Who knows

**Comment by samdauwe** [comment]
Yes, but I have never tried it.

This approach is currently used to bind the [Recast and Detour navigation library](https://github.com/recastnavigation/recastnavigation) to JavaScript in [this BabylonJS extension](https://github.com/BabylonJS/Extensions/tree/master/recastjs). A wrapper class is created that exposes a subset of the whole navigation library to javascript:
- Wrapper class for the navigation api is defined in the header: [recastjs.h](https://github.com/BabylonJS/Extensions/blob/master/recastjs/src/recastjs.h)
- WebIDL file describing the binding can be found in the [recast.idl](https://github.com/BabylonJS/Extensions/blob/master/recastjs/recast.idl) file. You can for instance see that the Vec3 struct in the header is described in the idl file as an interface.

The build scripts are also in the repo. Seems some work to configure everything and to define the WebIDL file but it works :)

The BabylonNative sample application works, but I did not try anything what you are working on.

**Comment by foxnoodles** [comment]
Wow, thanks for guiding me through all of these. I would never discover this stuff on my own. Gonna test everything now )

**Comment by samdauwe** [comment]
No real solutions yet to bind the BabylonCpp library to a react native application, but hopefully the provided links can help you further.

Good luck with testing out those approaches!
