### ISSUE TITLE
C2D WASM/React Native 

### ISSUE THREAD

**Issue by Sondro** [samdauwe/BabylonCpp#87]
Hi, I'm working on updating these runtimes (https://github.com/sondro/C2D-Web) & I'm interested in adding Babylon C++ for desktop & WASM.

The last issue thread is really long with outdated code & links.

Just curious what the current state or timeline is vs BabylonJS before I start playing with the code.

Also, is there React Native support or just solely DearImGUI?

Thanks.

**Comment by samdauwe** [comment]
Hi Sondro,

Thanks for your interest in Babylon C++ !!

The current state of BabylonJS is that I am working on bringing Babylon C++ in sync with BabylonJS v5.0.0-alpha.19. Due to many recent changes it is not advised to try out the latest version as it will probably not work at this moment. However, for a stable version in sync with the last [Babylon.js v4.2.0](https://doc.babylonjs.com/whats-new) release of 2020/11/12, please revert to this [commit](https://github.com/samdauwe/BabylonCpp/commit/cc2b6d6b386cb998501d70ecfadfc4fd0a5eba31). This version should give a good view of the current stable state. If you encounter any issues please let me know so I can further investigate.

There were also some efforts in creating a WASM version of Babylon C++ as you can see in this [issue thread](https://github.com/samdauwe/BabylonCpp/issues/2). You can try out the WASM version on [this link](https://traineq.org/BabylonStudio/BabylonStudio.html). Compared to the desktop version, this version has more issues (render artefacts, disappearing scenes, etc.) and debugging these issues were time consuming. Due to the lack of contributors I decided to only focus on the desktop version for now instead of maintaining/debugging two versions. So WASM is possible but it requires some effort to get it in the same state as the desktop version.

I had a brief look into your project [C2D-Web](https://github.com/sondro/C2D-Web), this is an interesting project! Nice work, especially the 200 mesh deforming raptor dinosaurs on screen are impressive. I would be interested on working together on adding Babylon C++ for desktop to your project. For instance, we could first create a separate branch to work on and then integrate [your code](https://github.com/Sondro/C2D-Web/tree/main/file/src/kit/CPP_WASM) for the mesh creation. From what I can see you are only using the core library and none of the extra libraries (i.e. procedural texture library) are therefore needed.

About the React Native support, this is not supported at this moment. because I never used this. At this moment only Dear ImGUI is supported. In case you are interested in adding support for React Native let me know.

Best regards,
Sam

**Comment by Sondro** [comment]
Well, firstly I want to say I'm not the creator of C2D or the tool, I'm just updating the outdated runtimes & demos + open to possibly porting them to other platforms. There is a runtime in C++ for UE4 4.26 from the actual developer: https://github.com/kestrelm/Creature_UE4

The C++ 3D engine ecosystem has a lot of competition (eg UE4 which has lots of free assents & learning content). The main benefit of this project I imagine would be for BabylonJS users who want desktop & WASM so they can create projects in each easily -- where other 3D engines like UE4 will be too 'heavy' & big for such projects.

I don't know if it will be worth it if the WASM will most likely never work (since Babylon is a web 3D engine -- that's where most of their users come from). Like I'm mainly curious in the difference between Babylon CPP WASM (if it worked) vs BabylonJS. I already know any C++ desktop implementation will be superior.

As for React Native -- that's what most web/mobile engineers use these days & it's very easy to theme. The main problem with DearImGUI is 99% of the interfaces appear identical & it seems difficult or complex to theme (don't know if they have improved this). I'd also be curious how well DearImGUI works in WASM web apps -- it's mostly used as a debugging/demo UI in C++.

**Comment by samdauwe** [comment]
Hi Sondro,

Ah, I was under the impression you were the creator of C2D. Then probably you don't want to put much effort in the desktop only version as you are mostly interested in the WASM version of BabylonCpp.

The benefit about BabylonCpp you mention is indeed the major selling point. Users can prototype in BabylonJS (with the existing tooling) for fast iterations and still have the option to target desktop for smaller runtime size and improved performance.

The difference between BabylonCpp WASM and BabylonJS greatly depends on the intended application. If you have a lot of game logic that is CPU bound then you can get a 2X performance (and more) improvement just by implementing the logic in WASM, for the numbers I can refer to [this page](https://itenium.be/blog/javascript/webassembly/). When your scene is very GPU bound, for instance if you have a lot of heavy shaders causing a high GPU load then the performance difference will not be that huge. With WASM it is also easier to achieve a stable framerate.

Yeah, most people use Dear ImGUI as a debug overlay and are not very worried about how it looks. Using it as a full user interface toolkit is not done often, however there good showcases such as [LumixEngine](https://github.com/nem0/LumixEngine). In case you want to try out Dear ImGUI in WASM I can refer you [this page](https://floooh.github.io/sokol-html5/imgui-sapp.html). Indeed, React Native looks much easier to theme compared to Dear ImGUI.

Best regards,
Sam

**Comment by Sondro** [comment]
Something to consider is a targeted Usability roadmap vs a broad Parity roadmap with BabylonJS. 

A Usability roadmap for most users might look something like:
- Working WASM
- Phong shading & flat colors
- glTF compression
- Basic normal & albedo maps
- Basic stencil shadows
- Pre-baked lighting
- Basic animating meshes
- Easy content import from Blender
- instancing
- cameras
- basic UI
- sprites/billboards
- heightmap terrain example
- skybox primitives
- client/server example
- Facebook ads/instant games example
- FPS example
- mobile UI example

Things like PBR materials are really slow for the web due to non-jpgs & pow2. Even on desktop, PBR requires libraries or special tools since most users cannot make them properly.

WebGL was originally based on OpenGL ES, but now it's being highly influenced by Vulkan & will become more Vulkan-like (C++, Rust, & Vulkan are developing new memory models & techniques over the years). Because of this it might be worth considering future proofing the project with a Vulkan build & then an OpenGL ES 2 build for high WASM compatibility. 

Obviously if you have to support WASM & Vulkan that's less time for all of these misc. features -- but again, how many people are actually using them? 

Another useful feature to consider would be coding your BabylonJS project in TypeScript & then transpiling it to C/C++ for BabylonCPP. Assuming your BabylonCPP supports WASM & you get the performance -- the lack of X engine extension is easily worth trading for the many JavaScript engineers who will forever be clueless & scared of C/C++.

**Comment by samdauwe** [comment]
Hi Sondro,

Thanks for the advice and feedback!

Indeed the development of BabylonJS goes really fast making it difficult to keep up feature wise. I was also thinking about taking the upcoming BabylonJS 5.0 as a target and then only work on usability for a long time, for instance on the topics you mentioned.

On your last comment, the BabylonJS project is actually coded in TypeScript but transpiling it to WASM is not their target. Porting the BabylonJS TypeScript codebase to AssemblyScript which can then be more easily transpiled to WASM seems to be the approach to achieve this.

On future proofing the project with Vulkan, that is a valid point. At this moment I am testing the upcoming WebGPU spec in [this repository](https://github.com/samdauwe/webgpu-native-examples), many examples are ports from the [Vulkan examples](https://github.com/SaschaWillems/Vulkan). I am currently targeting native (which uses the Vulkan backend on Linux) but in a few weeks when I have more examples I am going start working on the WASM version.

Best regards,
Sam

**Comment by Sondro** [comment]
Vulkan/Web GPU path seems like a good idea. I haven't checked in on web compatibility with Web GPU, but since Firefox is imploding you just really need to support the latest Chrome. 

I know that the BabylonJS WASM is not their target. My point is that if someone was experienced with BabylonJS & wanted to port their project to BabylonCpp their might be ways to ease this like typescript to C++ & some similar syntax to hook in (assuming the target audience of this project is BabylonJS users).

**Comment by samdauwe** [comment]
Indeed, WebGPU support in Firefox is behind the latest Chrome, but it is getting closer. Vulkan is also an option but this API does not compile to WASM. With WebGPU you can target WASM and it works on native too.

The target audience is BabylonJS users, familiar with the BabylonJS API and who do not want to invest time in learning another 3d framework to have native support using C++. The BabylonCpp API is similar to BabylonJS, there are a lot of examples demonstrating this. For Javascript and Typescript users who want both JavaScript/C++ there is [Babylon Native](https://github.com/BabylonJS/BabylonNative) officially supported by the BabylonJS team. For the moment I am not planning any JavaScript support for BabylonCpp, it look like too much work...

Best regards,
Sam
