### ISSUE TITLE
Is this project still alive (in development mode)?

### ISSUE THREAD

**Issue by danMaltaLightForce** [samdauwe/BabylonCpp#91]
Hi,

I wanted to say that this is an amazing project! beautifully crafted.
I wanted to ask if this project is still in development now that Babylon Native is "almost  good for production"?

**Comment by samdauwe** [comment]
Hi,

Thanks for the nice feedback!!

Keeping up with all the changes for Babylon.js v5.0 turned out to be too much effort for 1 person and the quality of this project was getting worse due to all the code changes. For these reasons, I stopped the development and the code is now back on an older stable Babylon.js v4.2.0 version.

Indeed, Babylon Native has become much more stable over the years, has many contributors and is officially supported and actively developed by the Babylon.js team, so I would recommend Babylon Native for native application development.
