### ISSUE TITLE
How long did it take and other questions

### ISSUE THREAD

**Issue by ghost** [samdauwe/BabylonCpp#92]
Hi,

- How long did it take to convert the TS codebase to CPP?
- What were the most difficult parts you encountered ?
- Compiling to wasm via emscripten sound good but I guess you already tried that. How was the experience so far ?
- Would you consider it to be worth the time investment <-> gains?

I may target version 6 when it's out. Hence the preparation work.

Thanks for your help and feedback

**Comment by samdauwe** [comment]
Hi,

How long did it take to convert the TS codebase to CPP?
- About 6 months when I started from scratch to get the [basic scene](https://playground.babylonjs.com/) on screen. I did not work on it full time only when I had available time.
- Porting the code to CPP after I had the first scene on screen has been a continuous effort (+/- 1 hour/day) to the current state

What were the most difficult parts you encountered ?
- Understanding the details of how some JavaScript/TypeScript code worked and how it could be translated to C++ (i.e. async behavior, ArrayBuffers, undefined variables, TypeScript syntax, etc.). Lifetime of objects when capturing them in Lambdas is different compared to JavaScript functions.
- Porting large changesets without breaking the whole code or cause side-effects in other examples
- Debugging examples when they do not completely render the same as the JavaScript version. It is not difficult but time-consuming.

Compiling to wasm via emscripten sound good but I guess you already tried that. How was the experience so far ?
- It has been a few years, but debugging was not easy. Also async loading of files is tricky.
- Some examples rendered fine on Desktop but not on Web so the emscripten effort was put on hold because of quality reasons and to save time to debug the issues

Would you consider it to be worth the time investment <-> gains?
- If your goals are:
   - to improve your C++ skills and knowledge on modern C++
   - to improve your Javascript/TypeScript skills and knowledge
   - getting better in working in large code bases and debugging
   - learn more about graphics APIs and how modern render engines work
   - => Definitely Yes
- If your goals is to maintain a C++ port of BabylonJS => definitely No
  - There is little interest in the port and you will get often requests that will make you shift focus a lot of the time (i.e. support MacOS, getting it working without without a specific library, etc.)
  - Not many people are interested in contributing or helping out for a long time
  - The amount of changes in Babylon.js has increased so much over the past years that is very difficult for one person to keep up with all the changes and maintaining a stable codebase where all examples still render fine (unless you are planning to work on it full time). 
  - [Babylon.js Native](https://www.babylonjs.com/native/) has a lot of contributors and is much more stable than my project ever was.

Porting to version 6 will be a huge effort, as the current code base is only maintained till version 4.x. I started the port to version 5, but stopped over time because it was too much work. If your goals are similar as the ones described above (first part) I would go for it.

From my side I shifted focus to my WebGPU examples project. It is a much nicer project to work on: there is no huge engine code base to maintain, I pick interesting examples and get something working on screen in a short time. Examples only break when there are changes in the WebGPU spec as there is not much common code shared between the examples.

Hope it helps,
Sam

**Comment by ghost** [comment]
It definitely helps, thanks a lot! I may step down to "just" assemblyscript and move on.. 
I should be much easier for me to maintain.

Not sure yet..

Sam, thanks a lot,
